import { ref, computed, onMounted, onUnmounted, markRaw } from "vue"
import { ToolCategory, ToolDef } from "./types"
// Icons
import {
	ImageIcon,
	FileTextIcon,
	KeyIcon,
	DatabaseIcon,
	ArrowRightIcon,
	HomeIcon,
	MenuIcon,
	XIcon,
	SunIcon,
	MoonIcon,
	SearchIcon,
	MicIcon,
	MusicIcon,
	FileCodeIcon,
	SmileIcon,
	UserIcon,
	Volume2Icon,
	WavesIcon,
	QrCodeIcon,
	AppWindowIcon,
	ScissorIcon,
	ScanIcon,
	GithubIcon,
	HelpCircleIcon,
	ChevronDownIcon,
} from "./components/Icon"

export const TOOLS = [
	{
		id: "ocr-tool",
		name: "Image to Text (OCR)",
		description: "Convert scanned documents and images into editable text using AI.",
		icon: markRaw(ScanIcon),
		category: ToolCategory.IMAGE,
		component: markRaw(OcrTool),
	},
	{
		id: "bg-remover",
		name: "Background Remover",
		description: "AI-powered background removal directly in your browser.",
		icon: markRaw(ScissorIcon),
		category: ToolCategory.IMAGE,
		component: markRaw(BackgroundRemover),
	},
	{
		id: "image-converter",
		name: "Image Converter",
		description: "Convert images to PNG, JPEG, or WEBP instantly in your browser.",
		icon: markRaw(ImageIcon),
		category: ToolCategory.IMAGE,
		component: markRaw(ImageConverter),
	},
	{
		id: "qr-gen",
		name: "QR Code Studio",
		description: "Create high-resolution QR codes with custom colors and formats.",
		icon: markRaw(QrCodeIcon),
		category: ToolCategory.IMAGE,
		component: markRaw(QrCodeGenerator),
	},
	{
		id: "pfp-creator",
		name: "Profile Pic Creator",
		description: "Create unique emoji avatars with custom backgrounds and shapes.",
		icon: markRaw(UserIcon),
		category: ToolCategory.IMAGE,
		component: markRaw(ProfilePictureCreator),
	},
	{
		id: "tts",
		name: "Text to Speech",
		description: "Convert written text into natural human speech using local AI.",
		icon: markRaw(Volume2Icon),
		category: ToolCategory.AUDIO,
		component: markRaw(TextToSpeech),
	},
	{
		id: "stt",
		name: "Speech to Text",
		description: "Transcribe your voice recordings into text accurately in real-time.",
		icon: markRaw(WavesIcon),
		category: ToolCategory.AUDIO,
		component: markRaw(SpeechToText),
	},
	{
		id: "audio-recorder",
		name: "Audio Recorder",
		description: "Record audio from your microphone and download locally.",
		icon: markRaw(MicIcon),
		category: ToolCategory.AUDIO,
		component: markRaw(AudioRecorder),
	},
	{
		id: "audio-converter",
		name: "Audio Converter",
		description: "Convert audio formats (MP3, WAV, etc.) using FFmpeg WASM.",
		icon: markRaw(MusicIcon),
		category: ToolCategory.AUDIO,
		component: markRaw(AudioConverter),
	},
]
